server:
  port: 9829
spring:
  application:
    name: ronaldo
  datasource:
    platform: POSTGRESQL
    continue-on-error: false
    url: jdbc:postgresql://localhost:5432/ronaldo
    username: capital
    password: capitaldb
    driver-class-name: org.postgresql.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    aibili:
      ronaldo:
        dao: debug
