server:
  port: 9829

spring:
  application:
    name: ronaldo
  datasource:
    platform: POSTGRESQL
    continue-on-error: false
    url: jdbc:postgresql://localhost:5432/ronaldo
    username: capital
    password: capitaldb
    driver-class-name: org.postgresql.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  session:
    store-type: none

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    aibili:
      ronaldo:
        dao: debug



